// Generated from backend/config/landmarks.yaml and games.yaml for the album design draft: the real landmark
// stories, a plausible Saturday-morning timeline, and dummy photos from picsum.photos (loaded only on
// the /album/preview page). Regenerate with scripts/album-mock.py; do not edit by hand.
import type { Album } from "./types";

export const PREVIEW_TOKEN = "preview";

export const MOCK_ALBUM: Album = {
  "game": "Sofia Old Town Quest",
  "team": "The Explorers",
  "time_zone": "Europe/Sofia",
  "played_on": "2026-10-03T07:30:00Z",
  "ended_at": "2026-10-03T10:28:00Z",
  "end_reason": "finished",
  "task_count": 6,
  "total_seconds": 12180,
  "rank": 2,
  "shared_rank": false,
  "host_message": "Thank you for exploring Sofia with us! Here is your journey, landmark by landmark – the riddles you cracked, the stories behind the places, and the photos you took along the way.",
  "chapters": [
    {
      "number": 1,
      "landmark": "Lily Pond",
      "landmark_i18n": {
        "de": "Seerosenteich",
        "sr": "Jezero s lokvanjima",
        "bg": "Езеро с лилии"
      },
      "story": "The pond was laid out by Daniel Neff, the Swiss gardener who first designed Borisova\nGarden, on the site of a former marsh. He stocked it with goldfish and planted water\nlilies. Because of the goldfish, it was known for many years as the Fish Pond. As early\nas around 1900 the pond appeared on some of Sofia's very first postcards. At that time\nit was decorated with an ornamental vase spouting water and with figures of frogs and\nturtles.\n\nOver the years the pond's appearance changed many times. In 1935 a large stone lily\nwith 36 jets of water was placed at its centre. Later, to a design by the sculptor\nVasil Zidarov, it was replaced by three bathing children. The boys have had an eventful\nhistory. By 2011 they had disappeared, and only a few frogs remained of the decoration.\nAfter bronze replicas, restored with corporate sponsorship, were stolen again, the\nmunicipality had the figures made from painted plastic. Today the bathing boys are back\nin their place, and some of the lilies in South Park were transplanted from this very\npond. A curious detail: the nearby drinking fountain was once topped with a bear, and\nnine penguins surrounded its spouts.",
      "story_i18n": {
        "de": "Den Teich legte Daniel Neff an, der Schweizer Gärtner, der als Erster den\nBorisova-Garten entwarf, an der Stelle eines ehemaligen Sumpfs. Er besetzte ihn mit\nGoldfischen und pflanzte Seerosen. Wegen der Goldfische war er über viele Jahre als\nFischteich bekannt. Schon um 1900 erschien der Teich auf einigen der allerersten\nPostkarten Sofias. Damals war er mit einer Ziervase mit Wasserspeier sowie mit\nFiguren von Fröschen und Schildkröten geschmückt.\n\nIm Laufe der Jahre veränderte der Teich sein Aussehen viele Male. 1935 wurde in\nseiner Mitte eine große steinerne Seerose mit 36 Wasserstrahlen aufgestellt. Später\nwurde sie nach einem Entwurf des Bildhauers Vasil Zidarov durch drei badende Kinder\nersetzt. Die Jungen haben eine wechselvolle Geschichte. Bis 2011 waren sie\nverschwunden, und von der Dekoration blieben nur ein paar Frösche. Nachdem\nBronzekopien, mit Firmenspenden restauriert, erneut gestohlen worden waren, ließ die\nGemeinde die Figuren aus bemaltem Kunststoff anfertigen. Heute sind die badenden\nJungen wieder an ihrem Platz, und manche der Seerosen im Südpark wurden genau aus\ndiesem Teich verpflanzt. Eine kuriose Einzelheit: Der nahe Trinkbrunnen war einst von\neinem Bären gekrönt, und neun Pinguine umgaben seine Wasserspeier.",
        "sr": "Jezero je uredio Danijel Nef, švajcarski baštovan koji je prvi projektovao Borisovu\nbaštu, na mestu nekadašnje močvare. Nastanio je u njemu zlatne ribice i posadio\nlokvanje. Zbog zlatnih ribica mnogo godina bio je poznat kao jezero sa ribama. Već\noko 1900. jezero se pojavilo na nekim od prvih sofijskih razglednica. Tada je bilo\nukrašeno ukrasnom vazom sa vodometom i figurama žaba i kornjača.\n\nKroz godine izgled jezera menjao se više puta. Godine 1935. u njegovom središtu\npostavljen je veliki kameni lokvanj sa 36 vodenih mlazeva. Kasnije je, po projektu\nvajara Vasila Zidarova, zamenjen trima dečacima koji se kupaju. Dečaci su imali burnu\nistoriju. Do 2011. su nestali, a od dekoracije je ostalo samo nekoliko žaba. Kada su\nbronzane kopije, obnovljene uz pomoć firmi, ponovo ukradene, gradska uprava je\nnaručila figure od farbane plastike. Danas su se kupajući dečaci vratili na svoje\nmesto, a neki lokvanji u Južnom parku presađeni su upravo sa ovog jezera. Zanimljiv\ndetalj: obližnja česma za piće nekada je bila okrunjena medvedom, a devet pingvina\nokruživalo je njene vodomete.",
        "bg": "Езерото е създадено от Даниел Неф, швейцарският градинар, който пръв проектира\nБорисовата градина, на мястото на някогашно блато. Той го напълнил със златни\nрибки и засадил водни лилии. Заради златните рибки дълги години е било известно\nкато Рибното езеро. Още около 1900 г. езерото се появява на едни от най-първите\nсофийски пощенски картички. Тогава то е било украсено с декоративна ваза с\nводна струя и с фигури на жаби и костенурки.\n\nС годините видът на езерото се е променял многократно. През 1935 г. в центъра му\nе поставена голяма каменна лилия с 36 водни струи. По-късно, по проект на\nскулптора Васил Зидаров, тя е заменена с три къпещи се деца. Момчетата имат\nбурна история. До 2011 г. те изчезват и от украсата остават само няколко жаби.\nСлед като бронзовите копия, възстановени с фирмени дарения, са откраднати\nотново, общината изработва фигурите от боядисана пластмаса. Днес къпещите се\nмомчета са отново на мястото си, а някои от лилиите в Южния парк са пресадени\nименно от това езеро. Любопитен детайл: близката чешма някога е била увенчана с\nмечка, а девет пингвина са обграждали струите ѝ."
      },
      "reached_at": "2026-10-03T07:58:00Z",
      "photos": [
        {
          "id": 1,
          "url": "https://picsum.photos/seed/lily-pond-1/1200/900",
          "taken_at": "2026-10-03T08:02:00Z"
        }
      ]
    },
    {
      "number": 2,
      "landmark": "Eagles' Bridge",
      "landmark_i18n": {
        "de": "Adlerbrücke",
        "sr": "Orlov most",
        "bg": "Орлов мост"
      },
      "story": "Eagles' Bridge (Orlov Most) was built in 1890–1891 over the Perlovska River and was one\nof the first solid masonry bridges erected in Sofia after the Liberation. For travellers\nentering the city from the east along Tsarigradsko Shose, it was the first crossroads\nleading into the centre proper, which is why it is called the city's gateway. The\nlocation was no accident. In March 1878, the Bulgarian prisoners and exiles freed from\nDiyarbakır were welcomed home on this very spot. For this reason, the bridge was\nconceived as a symbol of freedom. Today the event is marked by a modest stone plaque\nplaced by the municipality in the 1990s.\n\nThe bridge was designed by Sofia's chief architect, Adolf Václav Kolář, together with\nthe Czech engineer Václav Prošek, while its construction was entrusted to his cousins\nJiří and Bohdan Prošek. The same builders also erected Lions' Bridge, and Eagles' Bridge\nwas completed two years after it. The eagles and the metal parts were made in Vienna by\nthe firm Rudolph Philipp Waagner & Biró. The four bronze eagles with outstretched wings\nperch on columns of dressed granite about 7 metres high. According to interpreters,\ntheir number symbolises the four cardinal directions. The year of completion is\ninscribed on the richly decorated railings on both sides of the bridge. In 1970 the\nbridge was widened, and its northern railing was moved.",
      "story_i18n": {
        "de": "Die Adlerbrücke (Orlov Most) wurde 1890–1891 über die Perlovska errichtet und war\neine der ersten massiven Steinbrücken, die in Sofia nach der Befreiung gebaut wurden.\nFür Reisende, die von Osten über die Tsarigradsko Schosse in die Stadt kamen, war sie\ndie erste Kreuzung Richtung eigentlichem Zentrum – deshalb nennt man sie das Tor der\nStadt. Der Standort war kein Zufall. Im März 1878 wurden an genau dieser Stelle die\nbulgarischen Gefangenen und Verbannten, die aus Diyarbakır befreit worden waren, in\nder Heimat willkommen geheißen. Deshalb wurde die Brücke als Symbol der Freiheit\nkonzipiert. Heute erinnert eine bescheidene Steintafel, die die Gemeinde in den\n1990er Jahren anbrachte, an dieses Ereignis.\n\nEntworfen wurde die Brücke von Sofias Chefarchitekt Adolf Václav Kolář zusammen mit\ndem tschechischen Ingenieur Václav Prošek; den Bau übertrug man seinen Vettern Jiří\nund Bohdan Prošek. Dieselben Baumeister errichteten auch die Löwenbrücke, und die\nAdlerbrücke wurde zwei Jahre nach ihr vollendet. Die Adler und die Metallteile\nfertigte in Wien die Firma Rudolph Philipp Waagner & Biró. Die vier bronzegen Adler\nmit ausgebreiteten Flügeln sitzen auf Granitsäulen von etwa 7 Metern Höhe. Deutern\nzufolge symbolisiert ihre Zahl die vier Himmelsrichtungen. Das Jahr der Fertigstellung\nist auf den reich verzierten Geländern an beiden Seiten der Brücke eingraviert. 1970\nwurde die Brücke verbreitert, und ihr nördliches Geländer wurde versetzt.",
        "sr": "Orlov most sagrađen je 1890–1891. preko reke Perlovske i bio je jedan od prvih\nčvrstih kamenih mostova podignutih u Sofiji posle oslobođenja. Za putnike koji su u\ngrad ulazili s istoka, Carigradskim drumom, to je bila prva raskrsnica ka samom\ncentru — zato ga zovu kapija grada. Lokacija nije bila slučajna. U martu 1878. upravo\nna ovom mestu dočekani su u otadžbini bugarski zarobljenici i zatočenici oslobođeni\niz Dijarbakira. Zato je most zamišljen kao simbol slobode. Danas taj događaj obeležava\nskromna kamena ploča koju je gradska uprava postavila devedesetih godina prošlog\nveka.\n\nMost su projektovali sofijski glavni arhitekta Adolf Vaclav Kolar sa češkim\ninženjerom Vaclavom Prošekom, a gradnja je poverena njegovim rođacima Jiržiju i\nBohdanu Prošeku. Isti graditelji podigli su i Lavov most, a Orlov most je završen dve\ngodine posle njega. Orlovi i metalni delovi rađeni su u Beču, u firmi Rudolf Filip\nVagner i Biro. Četiri bronzana orla raširenih krila sede na stubovima od obrađenog\ngranita visokim oko 7 metara. Po tumačenjima, njihov broj simbolizuje četiri strane\nsveta. Godina završetka uklesana je na bogato ukrašenim gelenderima sa obe strane\nmosta. Godine 1970. most je proširen, a njegov severni gelender je pomeran.",
        "bg": "Орлов мост е построен през 1890–1891 г. над Перловска река и е бил един от\nпървите солидни каменни мостове, издигнати в София след Освобождението. За\nпътниците, които влизали в града от изток по Цариградско шосе, той е бил\nпървото кръстовище към самия център — затова го наричат портата на града.\nМястото не е случайно. През март 1878 г. точно тук са посрещнати българските\nзатворници и изгнаници, освободени от Диарбекир. Заради това мостът е замислен\nкато символ на свободата. Днес събитието е отбелязано със скромна каменна\nплоча, поставена от общината през 90-те години на миналия век.\n\nМостът е проектиран от главния архитект на София Адолф Вацлав Коларж заедно с\nчешкия инженер Вацлав Прошек, а строителството е поверено на неговите\nбратовчеди Иржи и Богдан Прошек. Същите строители издигат и Лъвовия мост, а\nОрлов мост е завършен две години след него. Орлите и металните части са\nизработени във Виена от фирмата „Рудолф Филип Вагнер & Биро“. Четирите\nбронзови орли с разперени крила седят върху колони от обработен гранит с\nвисочина около 7 метра. Според тълкуванията броят им символизира четирите\nпосоки на света. Годината на завършване е гравирана върху богато украсените\nперила от двете страни на моста. През 1970 г. мостът е разширен, а северното\nму перило е преместено."
      },
      "reached_at": "2026-10-03T08:22:00Z",
      "photos": [
        {
          "id": 2,
          "url": "https://picsum.photos/seed/eagles-bridge-1/1200/900",
          "taken_at": "2026-10-03T08:26:00Z"
        },
        {
          "id": 3,
          "url": "https://picsum.photos/seed/eagles-bridge-2/1200/900",
          "taken_at": "2026-10-03T08:29:00Z"
        }
      ]
    },
    {
      "number": 3,
      "landmark": "Sofia University (Rectorate)",
      "landmark_i18n": {
        "de": "Sofia-Universität (Rektorat)",
        "sr": "Sofijski univerzitet (Rektorat)",
        "bg": "Софийски университет (Ректорат)"
      },
      "story": "Evlogi and Hristo Georgiev were born in Karlovo. As young men they joined their\nmaternal uncles, the Puliev family, who were merchants in Romania. There the brothers\nbuilt up a large trading and banking business, while also supporting many institutions\nand paying for the education of numerous young people. In 1896 Evlogi donated 800,000\ngold leva and a plot of land in central Sofia for the building of the future university.\nHe died a year later. In his will he left 6 million leva for a higher school in Bulgaria\nand also acknowledged the contribution of his brother Hristo, who had died back in 1872\nat just 48. His relatives expected a large inheritance, but Evlogi left them only a few\nthousand leva and gave almost everything else to churches, schools, hospitals and\nuniversities. The two brothers are buried in Bellu Cemetery in Bucharest, and their tomb\nhas been declared an architectural monument by the Romanian state.\n\nThe road to the building was not an easy one. In 1906 an international design\ncompetition was won by the French architect Henri Bréasson, but construction never\nbegan. Later, the board managing the donation commissioned the architect Yordan Milanov\nto rework the design, despite objections from the university and from Bréasson himself.\nThe foundation stone was laid on 30 June 1924, and the building was solemnly consecrated\non 16 December 1934. Evlogi had asked for two marble statues to be erected in the\nschool's courtyard in memory of the brothers. Today they stand before the university's\ndoors, but they were cast in bronze. The two seated figures are the work of the sculptor\nKiril Shivarov.",
      "story_i18n": {
        "de": "Evlogi und Christo Georgiew wurden in Karlovo geboren. Als junge Männer schlossen sie\nsich den Brüdern ihrer Mutter an, der Familie Puliev, die in Rumänien Kaufleute waren.\nDort bauten die Brüder ein großes Handels- und Bankgeschäft auf und unterstützten\nzugleich viele Institutionen und bezahlten die Ausbildung zahlreicher junger Menschen.\n1896 stiftete Evlogi 800.000 Goldlewa und ein Grundstück im Zentrum Sofias für den Bau\nder künftigen Universität. Ein Jahr später starb er. In seinem Testament vermachte er\n6 Millionen Lewa für eine Hochschule in Bulgarien und würdigte auch den Anteil seines\nBruders Christo, der bereits 1872 im Alter von nur 48 Jahren gestorben war. Seine\nVerwandten erwarteten eine große Erbschaft, doch Evlogi hinterließ ihnen nur ein paar\nTausend Lewa und gab fast alles Übrige den Kirchen, Schulen, Krankenhäusern und\nUniversitäten. Die beiden Brüder sind auf dem Bellu-Friedhof in Bukarest begraben, und\nihr Grab wurde vom rumänischen Staat zum Architekturdenkmal erklärt.\n\nDer Weg zum Gebäude war nicht leicht. 1906 gewann der französische Architekt Henri\nBréasson einen internationalen Entwurfswettbewerb, doch der Bau begann nie. Später\nbeauftragte der Stiftungsrat den Architekten Yordan Milanov, den Entwurf zu\nüberarbeiten – trotz Einsprüchen der Universität und Bréassons selbst. Der Grundstein\nwurde am 30. Juni 1924 gelegt, und das Gebäude wurde am 16. Dezember 1934 feierlich\ngeweiht. Evlogi hatte gewünscht, dass im Hof der Schule zwei Marmorstatuen zum Gedenken\nan die Brüder errichtet werden. Heute stehen sie vor den Türen der Universität, aber\nsie wurden in Bronze gegossen. Die zwei sitzenden Figuren sind das Werk des Bildhauers\nKiril Shivarov.",
        "sr": "Evlogi i Hristo Georgijev rođeni su u Karlovu. Kao mladići pridružili su se ujacima sa\nmajčine strane, porodici Pulijev, trgovcima u Rumuniji. Tamo su braća izgradila veliku\ntrgovačku i bankarsku delatnost, a uz to pomažali su mnogim ustanovama i plaćali su\nškolovanje brojnim mladim ljudima. Godine 1896. Evlogi je poklonio 800.000 zlatnih leva\ni plac u središtu Sofije za podizanje budućeg univerziteta. Godinu dana kasnije umro\nje. U oporuci je ostavio 6 miliona leva za visoku školu u Bugarskoj i priznao je i\nzasluge brata Hrista, koji je umro još 1872. u svojoj 48. godini. Rođaci su očekivali\nveliku baštinu, ali im je Evlogi ostavio samo nekoliko hiljada leva, a skoro sve\nostalo poklonio je crkvama, školama, bolnicama i univerzitetima. Braća su sahranjena na\ngroblju Belju u Bukureštu, a njihovu grobnicu rumunska država proglasila je spomenikom\narhitekture.\n\nPut do zgrade nije bio lak. Godine 1906. na međunarodnom konkursu pobedio je francuski\narhitekta Anri Breason, ali gradnja nikada nije počela. Kasnije je odbor koji je\nupravljao zadužbinom poverio arhitekti Jordanu Milanovu da prerađuje projekat, uprkos\nprimedbama univerziteta i samog Breasona. Temeljni kamen položen je 30. juna 1924, a\nzgrada je svečano osvećena 16. decembra 1934. Evlogi je tražio da se u dvorištu škole\npodignu dve mermorne statue u spomen braći. Danas stoje pred vratima univerziteta, ali\nsu liveni u bronzi. Dve sede figure delo su vajara Kirila Šivarova.",
        "bg": "Евлоги и Христо Георгиеви са родени в Карлово. Като младежи се присъединили към\nбратята на майка си — семейство Пулиеви, които били търговци в Румъния. Там\nбратята изградили голяма търговско-банкова дейност, а в същото време подкрепяли\nмного институции и плащали образованието на множество млади хора. През 1896 г.\nЕвлоги дарява 800 000 златни лева и парцел в центъра на София за построяването на\nбъдещия университет. Година по-късно той умира. В завещанието си оставя 6 милиона\nлева за висше училище в България и признава приноса на брат си Христо, починал\nоще през 1872 г. едва на 48 години. Роднините му очаквали голямо наследство, но\nЕвлоги им оставил само няколко хиляди лева, а почти всичко останало дарил на\nцъркви, училища, болници и университети. Двамата братя са погребани в\nБукурещкото гробище Белу, а гробницата им е обявена от румънската държава за\nархитектурен паметник.\n\nПътят до сградата не е бил лесен. През 1906 г. международен конкурс печели\nфренският архитект Анри Бреасон, но строителството така и не започва. По-късно\nнастоятелството, което управлява дарението, възлага на архитекта Йордан Миланов\nда преработи проекта, въпреки възраженията на университета и на самия Бреасон.\nОсновният камък е положен на 30 юни 1924 г., а сградата е тържествено осветена на\n16 декември 1934 г. Евлоги е пожелал в двора на училището да бъдат издигнати две\nмраморни статуи в памет на братята. Днес те стоят пред вратите на университета,\nно са отлети от бронз. Двете седящи фигури са дело на скулптора Кирил Шиваров."
      },
      "reached_at": "2026-10-03T08:57:00Z",
      "photos": [
        {
          "id": 4,
          "url": "https://picsum.photos/seed/sofia-university-1/1200/900",
          "taken_at": "2026-10-03T09:01:00Z"
        }
      ]
    },
    {
      "number": 4,
      "landmark": "Alexander Nevsky Cathedral",
      "landmark_i18n": {
        "de": "Alexander-Newski-Kathedrale",
        "sr": "Katedrala Sv. Aleksandra Nevskog",
        "bg": "Катедрала „Свети Александър Невски“"
      },
      "story": "The St. Alexander Nevsky Cathedral was built in gratitude to the Russian liberators and\nbears the name of St. Alexander Nevsky, patron of the Russian army in the Russo-Turkish\nWar. The foundation stone was laid in 1882, and construction to a design by the\narchitect Alexander Pomerantsev lasted from 1904 to 1912. The mosaic icon of the saint\nis on the western façade, above the triple window, 30 metres above the ground.\n\nThe lion that gazes towards it is part of the Monument to the Unknown Soldier beside the\nSt. Sofia Church. It is the work of the sculptor Andrey Nikolov, who spent five years on\nit, from 1926 to 1931. The first monument, however, was rejected because it was\noverloaded with 17 sculpted figures. It was finally unveiled in 1941, and during the\nbombing of 1944 it was almost destroyed. For many years the lion moved from place to\nplace and was eventually found in the courtyard of a villa near Vrana. It was returned\nto its original spot when the new monument opened in 1981. Beside it burns an eternal\nflame, together with soil from Shipka and Stara Zagora, where the heaviest losses of the\nLiberation War were suffered. Today the four-metre bronze lion is polished smooth by the\nchildren who climb on it.",
      "story_i18n": {
        "de": "Die Kathedrale St. Alexander Newski wurde in Dankbarkeit gegenüber den russischen\nBefreiern erbaut und trägt den Namen des heiligen Alexander Newski, des Schutzpatrons\nder russischen Armee im Russisch-Türkischen Krieg. Der Grundstein wurde 1882 gelegt,\nund der Bau nach dem Entwurf des Architekten Alexander Pomeranzew dauerte von 1904 bis\n1912. Das Mosaikbild des Heiligen befindet sich an der Westfassade, über dem\ndreifach gegliederten Fenster, 30 Meter über dem Boden.\n\nDer Löwe, der zu ihm hinaufblickt, gehört zum Denkmal des unbekannten Soldaten neben\nder Kirche St. Sofia. Es ist das Werk des Bildhauers Andrej Nikolow, der fünf Jahre an\nihm arbeitete, von 1926 bis 1931. Das erste Denkmal wurde jedoch abgelehnt, weil es\nmit 17 Skulpturfiguren überladen war. Schließlich wurde es 1941 enthüllt, und bei den\nBombardierungen 1944 wurde es beinahe zerstört. Viele Jahre wanderte der Löwe von Ort\nzu Ort und wurde schließlich im Hof einer Villa nahe Vrana gefunden. Er kehrte an\nseinen ursprünglichen Platz zurück, als das neue Denkmal 1981 eingeweiht wurde. Daneben\nbrennt ein ewiges Feuer, zusammen mit Erde von Schipka und Stara Sagora, wo die\nschwersten Verluste des Befreiungskrieges zu beklagen waren. Heute ist der vier Meter\nhohe Bronzelöwe von den Kindern, die auf ihm klettern, glatt poliert.",
        "sr": "Katedrala Sv. Aleksandra Nevskog sagrađena je u znak zahvalnosti ruskim oslobodiocima\ni nosi ime Sv. Aleksandra Nevskog, zaštitnika ruske armije u rusko-turskom ratu.\nTemeljni kamen položen je 1882, a gradnja po projektu arhitekte Aleksandra\nPomeranceva trajala je od 1904. do 1912. Mozaik ikone sveca nalazi se na zapadnoj\nfasadi, iznad trostrukog prozora, 30 metara nad zemljom.\n\nLav koji gleda u nju deo je Spomenika nepoznatom vojniku pored crkve Sv. Sofia. Delo\nje vajara Andreja Nikolova, koji je na njemu radio pet godina, od 1926. do 1931. Prvi\nspomenik je, međutim, odbijen jer je bio pretrpan sa 17 skulptura. Konačno je otkriven\n1941, a tokom bombardovanja 1944. bio je na ivici uništenja. Mnogo godina lav je\nseljen s mesta na mesto i na kraju je pronađen u dvorištu vile kod Vrane. Vraćen je na\nprvobitno mesto kada je 1981. otvoren novi spomenik. Pored njega gori večni oganj,\nzajedno sa zemljom sa Šipke i Stare Zagore, gde su u oslobođenačkom ratu bili najteži\ngubici. Danas je bronzani lav visok četiri metra uglačan do glatkoće od dece koja se\npenju po njemu.",
        "bg": "Катедралата „Свети Александър Невски“ е построена в знак на благодарност към\nруските освободители и носи името на свети Александър Невски, покровител на\nруската армия в Руско-турската война. Основният камък е положен през 1882 г., а\nстроителството по проект на архитекта Александър Померанцев продължава от 1904 до\n1912 г. Мозайката с иконата на светеца е на западната фасада, над тройния\nпрозорец, на 30 метра над земята.\n\nЛъвът, който гледа към нея, е част от Паметника на незнайния войник до църквата\n„Света София“. Той е дело на скулптора Андрей Николов, работил върху него пет\nгодини, от 1926 до 1931 г. Първият паметник обаче е отхвърлен, защото е бил\nпретоварен със 17 скулптурни фигури. Най-накрая е открит през 1941 г., а по време\nна бомбардировките през 1944 г. едва не е унищожен. Дълги години лъвът е местен от\nмясто на място и накрая е открит в двора на вила край Врана. Върнат е на\nпървоначалното си място, когато през 1981 г. е открит новият паметник. До него\nгори вечен огън, заедно със земя от Шипка и Стара Загора, където са най-тежките\nзагуби на Освободителната война. Днес четириметровият бронзов лъв е лъснат до\nгладкост от децата, които се катерят по него."
      },
      "reached_at": "2026-10-03T09:28:00Z",
      "photos": [
        {
          "id": 5,
          "url": "https://picsum.photos/seed/alexander-nevsky-1/1200/900",
          "taken_at": "2026-10-03T09:32:00Z"
        },
        {
          "id": 6,
          "url": "https://picsum.photos/seed/alexander-nevsky-2/1200/900",
          "taken_at": "2026-10-03T09:35:00Z"
        },
        {
          "id": 7,
          "url": "https://picsum.photos/seed/alexander-nevsky-3/1200/900",
          "taken_at": "2026-10-03T09:38:00Z"
        }
      ]
    },
    {
      "number": 5,
      "landmark": "Ivan Vazov National Theatre",
      "landmark_i18n": {
        "de": "Nationales Theater Ivan Vazov",
        "sr": "Narodno pozorište Ivan Vazov",
        "bg": "Народен театър „Иван Вазов“"
      },
      "story": "The building was designed by the Viennese architects Ferdinand Fellner and Hermann\nHelmer, known as \"the opera architects\" because they built more than 50 theatres across\nEurope. It stands on the site of the wooden Osnova Theatre, and the National Assembly\npassed a special law to raise funds for its construction. The theatre opened on 3\nJanuary 1907 with Ivan Vazov's play The Lost Ones. The opening was a stormy one:\nstudents booed Prince Ferdinand on his arrival, and he closed Sofia University for six\nmonths in response. Above the entrance, six columns support a triangular pediment\nshowing Apollo, the patron of the arts, surrounded by the muses.\n\nWithin just a few days in 1923, the building went through two ordeals. On 4 February,\nduring a performance, a bomb was thrown at Prime Minister Aleksandar Stamboliyski, but\nno one was killed and the show went on. A week later, on 10 February, during an\nanniversary performance using gas lighting, a lamp set fire to the wooden parts of the\nstage. The blaze destroyed almost the entire building, and only the façade survived. The\ntheatre was rebuilt by the German architect Martin Dülfer and the Bulgarian engineer\nKiril Chaparov, and the new stage had a movable floor, a revolutionary technology for\nits time. The building was damaged again by bombing during the Second World War, and in\n1974–1976 its original appearance was restored.",
      "story_i18n": {
        "de": "Das Gebäude entwarfen die Wiener Architekten Ferdinand Fellner und Hermann Helmer,\nbekannt als „die Opernarchitekten\", weil sie mehr als 50 Theater in ganz Europa\nbauten. Es steht an der Stelle des hölzernen Theaters Osnova, und die\nNationalversammlung erließ ein Sondergesetz, um Gelder für seinen Bau zu sammeln.\nEröffnet wurde das Theater am 3. Januar 1907 mit Ivan Vazovs Stück „Die Verlorenen\".\nDie Eröffnung verlief stürmisch: Studenten buhten Fürst Ferdinand bei seiner Ankunft\naus, und dieser schloss als Reaktion die Sofia-Universität für sechs Monate. Über dem\nEingang tragen sechs Säulen einen dreieckigen Giebel, der Apollon, den Schutzpatron der\nKünste, zeigt, umgeben von den Musen.\n\nInnerhalb von nur wenigen Tagen im Jahr 1923 erlebte das Gebäude zwei Prüfungen. Am\n4. Februar wurde während einer Vorstellung ein Sprengsatz auf Ministerpräsident\nAleksandar Stamboliyski geworfen, doch niemand kam ums Leben und die Vorstellung ging\nweiter. Eine Woche später, am 10. Februar, setzte während einer Jubiläumsvorstellung\nmit Gasbeleuchtung eine Lampe die hölzernen Teile der Bühne in Brand. Das Feuer\nzerstörte fast das gesamte Gebäude; nur die Fassade überlebte. Das Theater wurde vom\ndeutschen Architekten Martin Dülfer und dem bulgarischen Ingenieur Kiril Chaparov\nwiederaufgebaut, und die neue Bühne erhielt einen beweglichen Boden, eine\nrevolutionäre Technik ihrer Zeit. Im Zweiten Weltkrieg wurde das Gebäude erneut durch\nBomben beschädigt, und 1974–1976 stellte man sein ursprüngliches Aussehen wieder her.",
        "sr": "Zgradu su projektovali bečki arhitekti Ferdinand Felner i Herman Helmer, poznati kao\n„arhitekti opera\", jer su sagradili više od 50 pozorišta širom Evrope. Ona stoji na\nmestu drvenog pozorišta Osnova, a Narodna skupština donela je poseban zakon da prikupi\nsredstva za njenu gradnju. Pozorište je otvoreno 3. januara 1907. Vazovljevom dramom\n„Izgubljeni\". Otvorenje je bilo burno: studenti su zviždali kneza Ferdinanda pri\ndolasku, a on je, kao odgovor, zatvorio Sofijski univerzitet na šest meseci. Iznad\nulaza šest stubova nosi trougaoni zabat na kome je Apolon, zaštitnik umetnosti,\nokružen muzama.\n\nU svega nekoliko dana 1923. zgrada je prošla kroz dva iskušenja. 4. februara, tokom\npredstave, na premijera Aleksandara Stambolijskog bačena je bomba, ali niko nije\nstradao i predstava je nastavljena. Nedelju dana kasnije, 10. februara, tokom\nsvečane predstave sa gasnim osvetljenjem lampa je zapalila drvene delove bine. Plamen\nje uništio skoro celu zgradu; preživela je samo fasada. Pozorište su obnovili nemački\narhitekta Martin Dilfer i bugarski inženjer Kiril Čaparov, a nova bina je imala\npokretni pod, revolucionarnu tehnologiju za ono vreme. Zgrada je ponovo oštećena\nbombardovanjem u Drugom svetskom ratu, a 1974–1976. obnovljen je njen prvobitni\nizgled.",
        "bg": "Сградата е проектирана от виенските архитекти Фердинанд Фелнер и Херман Хелмер,\nизвестни като „архитектите на оперите“, защото са построили повече от 50 театъра\nиз цяла Европа. Тя стои на мястото на дървения театър „Основа“, а Народното\nсъбрание приема специален закон за събиране на средства за строителството ѝ.\nТеатърът е открит на 3 януари 1907 г. с пиесата на Иван Вазов „Изгубените“.\nОткриването е бурно: студенти освиркват княз Фердинанд при пристигането му, а той\nв отговор затваря Софийския университет за шест месеца. Над входа шест колони\nподдържат триъгълен фронтон с Аполон, покровителя на изкуствата, заобиколен от\nмузите.\n\nВ рамките на само няколко дни през 1923 г. сградата преминава през две изпитания.\nНа 4 февруари по време на представление е хвърлена бомба срещу\nминистър-председателя Александър Стамболийски, но никой не загива и\nпредставлението продължава. Седмица по-късно, на 10 февруари, по време на\nюбилейно представление с газово осветление лампа подпалва дървените части на\nсцената. Пламъкът унищожава почти цялата сграда и оцелява само фасадата. Театърът\nе възстановен от немския архитект Мартин Дюлфер и българския инженер Кирил\nЧапаров, а новата сцена има подвижен под — революционна технология за времето си.\nСградата е повредена отново при бомбардировките през Втората световна война, а\nпрез 1974–1976 г. е възстановен първоначалният ѝ вид."
      },
      "reached_at": "2026-10-03T09:50:00Z",
      "photos": [
        {
          "id": 8,
          "url": "https://picsum.photos/seed/ivan-vazov-theatre-1/1200/900",
          "taken_at": "2026-10-03T09:54:00Z"
        }
      ]
    },
    {
      "number": 6,
      "landmark": "Ancient Serdika Complex",
      "landmark_i18n": {
        "de": "Antikes Serdika",
        "sr": "Antička Serdika",
        "bg": "Античен комплекс „Сердика“"
      },
      "story": "The remains of the Roman city were uncovered between 2010 and 2012, during the\nconstruction of the Serdika 2 metro station. The discoveries include parts of the city's\ntwo main streets: the Cardo Maximus, which linked the northern and southern gates, and\nthe Decumanus Maximus, which linked the eastern and western gates. The two met at a\nright angle, and the forum, the city's central square, stood at their crossing. The\nstreet on the sign is one of the secondary streets that formed the city's grid. It is 5\nmetres wide, 10 metres of it have been excavated, and its paving dates from the 6th\ncentury. Beneath it, parts of the ancient water supply and sewage system are on display,\nproof that Serdica was a well-planned city.\n\nThe complex was officially opened in 2016 after six years of work by around a hundred\narchaeologists and five architects. It covers 8,000 square metres and, at its opening,\nwas presented as the largest open-air museum in the Balkans. Under the glass dome\nbetween the Presidency and the Council of Ministers, a stage has been set up with the\nruins of Serdica as its backdrop. Near the entrance to the metro station there are also\nremains of an early Christian basilica from the 4th century.",
      "story_i18n": {
        "de": "Die Reste der römischen Stadt wurden zwischen 2010 und 2012 beim Bau der Metrostation\nSerdika 2 freigelegt. Zu den Entdeckungen gehören Teile der beiden Hauptstraßen der\nStadt: der Cardo Maximus, der das Nord- und das Südtor verband, und der Decumanus\nMaximus, der das Ost- und das Westtor verband. Die beiden trafen sich im rechten\nWinkel, und das Forum, der zentrale Platz der Stadt, stand an ihrer Kreuzung. Die\nStraße auf dem Schild ist eine der Nebenstraßen, die das Raster der Stadt bildeten. Sie\nist 5 Meter breit, 10 Meter davon sind ausgegraben, und ihr Pflaster stammt aus dem 6.\nJahrhundert. Darunter sind Teile der antiken Wasserversorgung und Kanalisation zu\nsehen – ein Beweis dafür, dass Serdika eine gut geplante Stadt war.\n\nDer Komplex wurde 2016 offiziell eröffnet, nach sechs Jahren Arbeit von rund hundert\nArchäologen und fünf Architekten. Er umfasst 8.000 Quadratmeter und wurde bei seiner\nEröffnung als das größte Freilichtmuseum auf dem Balkan vorgestellt. Unter der\nGlaskuppel zwischen der Präsidentschaft und dem Ministerrat wurde eine Bühne\neingerichtet, mit den Ruinen Serdikas als Kulisse. Nahe dem Eingang zur Metrostation\nsind auch Reste einer frühchristlichen Basilika aus dem 4. Jahrhundert zu sehen.",
        "sr": "Ostaci rimskog grada otkriveni su između 2010. i 2012, tokom gradnje metro stanice\nSerdika 2. Među otkrićima su delovi dve glavne ulice grada: Cardo Maximus, koji je\nspajao severnu i južnu kapiju, i Decumanus Maximus, koji je spajao istočnu i zapadnu\nkapiju. Sekle su se pod pravim uglom, a na njihovom ukrštanju stajao je forum, glavni\ntrg grada. Ulica na tabli jedna je od sporednih ulica koje su činile mrežu grada.\nŠiroka je 5 metara, iskopano je 10 metara, a njena kaldrma potiče iz 6. veka. Ispod\nnje su izloženi delovi drevnog vodovoda i kanalizacije — dokaz da je Serdika bilo\ndobro planiran grad.\n\nKompleks je zvanično otvoren 2016. posle šest godina rada stotinak arheologa i pet\narhitekata. Prostire se na 8.000 kvadratnih metara i pri otvorenju je predstavljen\nkao najveći muzej na otvorenom na Balkanu. Ispod staklene kupole između Predsedništva\ni Saveta ministara postavljena je bina sa ruševinama Serdike kao pozadinom. U blizini\nulaza u metro stanicu nalaze se i ostaci ranohrišćanske bazilike iz 4. veka.",
        "bg": "Останките на римския град са разкрити между 2010 и 2012 г. по време на\nстроителството на метростанция „Сердика 2“. Сред откритията са части от двете\nглавни улици на града: Кардо Максимус, който свързвал северната и южната порта, и\nДекуманус Максимус, който свързвал източната и западната порта. Двете се\nпресичали под прав ъгъл, а на кръстовището им стоял форумът — централният\nплощад на града. Улицата от табелата е една от вторичните улици, образували\nградската мрежа. Тя е широка 5 метра, разкопани са 10 метра от нея, а паважът ѝ\nдатира от VI век. Под нея са изложени части от древния водопровод и канализация —\nдоказателство, че Сердика е бил добре планиран град.\n\nКомплексът е официално открит през 2016 г. след шест години работа на около сто\nархеолози и петима архитекти. Той се простира на 8 000 квадратни метра и при\nоткриването си е представен като най-големият музей на открито на Балканите. Под\nстъкления купол между Президентството и Министерския съвет е обособена сцена с\nруините на Сердика като фон. Близо до входа на метростанцията са запазени и\nостанки от раннохристиянска базилика от IV век."
      },
      "reached_at": "2026-10-03T10:16:00Z",
      "photos": [
        {
          "id": 9,
          "url": "https://picsum.photos/seed/ancient-serdika-1/1200/900",
          "taken_at": "2026-10-03T10:20:00Z"
        },
        {
          "id": 10,
          "url": "https://picsum.photos/seed/ancient-serdika-2/1200/900",
          "taken_at": "2026-10-03T10:23:00Z"
        }
      ]
    }
  ]
};
